version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: db0
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d db0"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: gomicro/goose:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=postgres port=5432 user=test password=test dbname=db0 sslmode=disable"
    volumes:
      - ../db/migrations:/migrations
    command: ["goose", "-dir", "/migrations", "up"]
    restart: on-failure

  tests:
    build:
      context: ..
      dockerfile: build/deploy/Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      APP_ENV: "smoke"
    command: ["go", "test", "-v", "./..."]
    profiles: ["tests"]
